### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by WenyuLiang** [paoloshasta/shasta#5] opened 2022-11-07 19:10 UTC
Hi Paolo, 
After I upgraded Shasta to 0.11.0, it always gives me the same error even if I use exactly same parameters as Shasta 0.10.0.
New configurations also give the same error. 
<img width="561" alt="Screenshot 2022-11-07 at 11 10 12 AM" src="https://user-images.githubusercontent.com/86228331/200394319-cd835c27-e8a7-4707-a583-63396ca930d8.png">

**Comment by paoloshasta** [comment] 2022-11-07 19:16
What Linux distribution/version are you using? Is this an x86_64 or ARM machine? Please also attach the output of the following two commands:

- `uname -a`
- `head -28 /proc/cpuinfo`

**Comment by WenyuLiang** [comment] 2022-11-07 20:36
NAME="Ubuntu"
VERSION="20.04

Linux wenyu1 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 2
model name	: AMD Opteron 63xx class CPU
stepping	: 0
microcode	: 0x1000065
cpu MHz		: 2299.998
cache size	: 512 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx pdpe1gb lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx f16c hypervisor lahf_lm abm sse4a misalignsse 3dnowprefetch xop fma4 tbm vmmcall arat
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4599.99
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management:

**Comment by paoloshasta** [comment] 2022-11-07 20:49
Thank you. Please also attach the last few lines of standard output, and the last few lines of `performance.log` in the assembly directory, if present.

**Comment by paoloshasta** [comment] 2022-11-07 20:51
Does the same crash occur without `--memoryMode filesystem --memoryBacking 2M`? I am trying to narrow down the problem, in the hope that I can reproduce it.

**Comment by paoloshasta** [comment] 2022-11-07 21:00
I would like to know the opcode of the offending instruction. Can you see if any error messages are generated on `/var/log/syslog` or `/var/log/dmesg` when the crash occurs? If so, please attach them here.

**Comment by paoloshasta** [comment] 2022-11-07 21:31
Does the last line of `performance.log` say `assembleMarkerGraqhEdges begins` following a timestamp? If so, I have been able to reproduce the problem on an old laptop.

**Comment by paoloshasta** [comment] 2022-11-07 21:52
I attached here a test executable with a tentative fix that eliminated the crash for me. Please let me know if this works for you. If it does, I will create soon a new Shasta release with the fix.The attached executable is gzipped - you will have to `gunzip` it before running it, of course.

The Shasta 0.11.0 executable uses some processor instructions that are missing in older processors such as yours, and my old laptop. This was due to an error in the Shasta build process whch was recently introduced, and which I now fixed.

If this executable does not fix the problem for you, please provide the information I requested in my last few posts, and we can continue from there.

[shasta.gz](https://github.com/paoloshasta/shasta/files/9955719/shasta.gz)

**Comment by WenyuLiang** [comment] 2022-11-08 16:50
Hi Paolo, sorry for the late reply. The shasta.gz works on my machine! Thanks for your help.

**Comment by paoloshasta** [comment] 2022-11-08 16:56
Thank you for confirming this, and for reporting the problem in the first place. I also fixed another bug (issue #4), so I will probably create a new release with these two fixes.

**Comment by paoloshasta** [comment] 2022-11-08 18:02
This fixed in [Shasta 0.11.1](https://github.com/paoloshasta/shasta/releases/tag/0.11.1).

**Closed by paoloshasta** 2022-11-08 18:02 UTC
Labels: bug
